import type { Market } from '@/lib/types/market';

/**
 * Static market configuration
 * This replaces Supabase queries for the home page
 * Generated from supabase/migrations/20250820_005_complete_setup.sql
 */

export const markets: Market[] = [
  // Tier 1 - Major Markets
  {
    id: 'nyse-market-id',
    slug: 'nyse',
    name: 'New York Stock Exchange',
    short_name: 'NYSE',
    country: 'United States',
    flag_emoji: '🇺🇸',
    city: 'New York',
    timezone: 'America/New_York',
    tier: 1,
    position: 1,
    is_active: true,
  },
  {
    id: 'nasdaq-market-id',
    slug: 'nasdaq',
    name: 'NASDAQ',
    short_name: 'NASDAQ',
    country: 'United States',
    flag_emoji: '🇺🇸',
    city: 'New York',
    timezone: 'America/New_York',
    tier: 1,
    position: 2,
    is_active: true,
  },
  {
    id: 'lse-market-id',
    slug: 'lse',
    name: 'London Stock Exchange',
    short_name: 'LSE',
    country: 'United Kingdom',
    flag_emoji: '🇬🇧',
    city: 'London',
    timezone: 'Europe/London',
    tier: 1,
    position: 3,
    is_active: true,
  },
  {
    id: 'euronext-paris-market-id',
    slug: 'euronext-paris',
    name: 'Euronext (Paris)',
    short_name: 'ENX',
    country: 'France',
    flag_emoji: '🇪🇺',
    city: 'Paris',
    timezone: 'Europe/Paris',
    tier: 1,
    position: 4,
    is_active: true,
  },
  {
    id: 'xetra-market-id',
    slug: 'xetra',
    name: 'Deutsche Börse (Xetra)',
    short_name: 'XETRA',
    country: 'Germany',
    flag_emoji: '🇩🇪',
    city: 'Frankfurt',
    timezone: 'Europe/Berlin',
    tier: 1,
    position: 5,
    is_active: true,
  },
  {
    id: 'tse-market-id',
    slug: 'tse',
    name: 'Tokyo Stock Exchange',
    short_name: 'TSE',
    country: 'Japan',
    flag_emoji: '🇯🇵',
    city: 'Tokyo',
    timezone: 'Asia/Tokyo',
    tier: 1,
    position: 6,
    is_active: true,
  },
  {
    id: 'hkex-market-id',
    slug: 'hkex',
    name: 'Hong Kong Stock Exchange',
    short_name: 'HKEX',
    country: 'Hong Kong',
    flag_emoji: '🇭🇰',
    city: 'Hong Kong',
    timezone: 'Asia/Hong_Kong',
    tier: 1,
    position: 7,
    is_active: true,
  },
  {
    id: 'sse-market-id',
    slug: 'sse',
    name: 'Shanghai Stock Exchange',
    short_name: 'SSE',
    country: 'China',
    flag_emoji: '🇨🇳',
    city: 'Shanghai',
    timezone: 'Asia/Shanghai',
    tier: 1,
    position: 8,
    is_active: true,
  },
  {
    id: 'szse-market-id',
    slug: 'szse',
    name: 'Shenzhen Stock Exchange',
    short_name: 'SZSE',
    country: 'China',
    flag_emoji: '🇨🇳',
    city: 'Shenzhen',
    timezone: 'Asia/Shanghai',
    tier: 1,
    position: 9,
    is_active: true,
  },
  {
    id: 'nse-market-id',
    slug: 'nse',
    name: 'National Stock Exchange of India',
    short_name: 'NSE',
    country: 'India',
    flag_emoji: '🇮🇳',
    city: 'Mumbai',
    timezone: 'Asia/Kolkata',
    tier: 1,
    position: 10,
    is_active: true,
  },

  // Tier 2 - Regional Markets
  {
    id: 'tsx-market-id',
    slug: 'tsx',
    name: 'Toronto Stock Exchange',
    short_name: 'TSX',
    country: 'Canada',
    flag_emoji: '🇨🇦',
    city: 'Toronto',
    timezone: 'America/Toronto',
    tier: 2,
    position: 1,
    is_active: true,
  },
  {
    id: 'asx-market-id',
    slug: 'asx',
    name: 'Australian Securities Exchange',
    short_name: 'ASX',
    country: 'Australia',
    flag_emoji: '🇦🇺',
    city: 'Sydney',
    timezone: 'Australia/Sydney',
    tier: 2,
    position: 2,
    is_active: true,
  },
  {
    id: 'krx-market-id',
    slug: 'krx',
    name: 'Korea Exchange',
    short_name: 'KRX',
    country: 'South Korea',
    flag_emoji: '🇰🇷',
    city: 'Seoul',
    timezone: 'Asia/Seoul',
    tier: 2,
    position: 3,
    is_active: true,
  },
  {
    id: 'sgx-market-id',
    slug: 'sgx',
    name: 'Singapore Exchange',
    short_name: 'SGX',
    country: 'Singapore',
    flag_emoji: '🇸🇬',
    city: 'Singapore',
    timezone: 'Asia/Singapore',
    tier: 2,
    position: 4,
    is_active: true,
  },
  {
    id: 'twse-market-id',
    slug: 'twse',
    name: 'Taiwan Stock Exchange',
    short_name: 'TWSE',
    country: 'Taiwan',
    flag_emoji: '🇹🇼',
    city: 'Taipei',
    timezone: 'Asia/Taipei',
    tier: 2,
    position: 5,
    is_active: true,
  },
  {
    id: 'omx-stockholm-market-id',
    slug: 'omx-stockholm',
    name: 'OMX Stockholm',
    short_name: 'OMX',
    country: 'Sweden',
    flag_emoji: '🇸🇪',
    city: 'Stockholm',
    timezone: 'Europe/Stockholm',
    tier: 2,
    position: 6,
    is_active: true,
  },
  {
    id: 'six-swiss-market-id',
    slug: 'six-swiss',
    name: 'SIX Swiss Exchange',
    short_name: 'SIX',
    country: 'Switzerland',
    flag_emoji: '🇨🇭',
    city: 'Zurich',
    timezone: 'Europe/Zurich',
    tier: 2,
    position: 7,
    is_active: true,
  },
  {
    id: 'bit-market-id',
    slug: 'bit',
    name: 'Borsa Italiana',
    short_name: 'BIT',
    country: 'Italy',
    flag_emoji: '🇮🇹',
    city: 'Milan',
    timezone: 'Europe/Rome',
    tier: 2,
    position: 8,
    is_active: true,
  },
  {
    id: 'bme-market-id',
    slug: 'bme',
    name: 'Bolsas y Mercados Españoles',
    short_name: 'BME',
    country: 'Spain',
    flag_emoji: '🇪🇸',
    city: 'Madrid',
    timezone: 'Europe/Madrid',
    tier: 2,
    position: 9,
    is_active: true,
  },
  {
    id: 'vse-market-id',
    slug: 'vse',
    name: 'Vienna Stock Exchange',
    short_name: 'VSE',
    country: 'Austria',
    flag_emoji: '🇦🇹',
    city: 'Vienna',
    timezone: 'Europe/Vienna',
    tier: 2,
    position: 10,
    is_active: true,
  },

  // Tier 3 - Emerging Markets
  {
    id: 'bmv-market-id',
    slug: 'bmv',
    name: 'Bolsa Mexicana de Valores',
    short_name: 'BMV',
    country: 'Mexico',
    flag_emoji: '🇲🇽',
    city: 'Mexico City',
    timezone: 'America/Mexico_City',
    tier: 3,
    position: 1,
    is_active: true,
  },
  {
    id: 'b3-market-id',
    slug: 'b3',
    name: 'B3 (Brasil Bolsa Balcão)',
    short_name: 'B3',
    country: 'Brazil',
    flag_emoji: '🇧🇷',
    city: 'São Paulo',
    timezone: 'America/Sao_Paulo',
    tier: 3,
    position: 2,
    is_active: true,
  },
  {
    id: 'bcs-market-id',
    slug: 'bcs',
    name: 'Bolsa de Comercio de Santiago',
    short_name: 'BCS',
    country: 'Chile',
    flag_emoji: '🇨🇱',
    city: 'Santiago',
    timezone: 'America/Santiago',
    tier: 3,
    position: 3,
    is_active: true,
  },
  {
    id: 'jse-market-id',
    slug: 'jse',
    name: 'Johannesburg Stock Exchange',
    short_name: 'JSE',
    country: 'South Africa',
    flag_emoji: '🇿🇦',
    city: 'Johannesburg',
    timezone: 'Africa/Johannesburg',
    tier: 3,
    position: 4,
    is_active: true,
  },
  {
    id: 'egx-market-id',
    slug: 'egx',
    name: 'Egyptian Exchange',
    short_name: 'EGX',
    country: 'Egypt',
    flag_emoji: '🇪🇬',
    city: 'Cairo',
    timezone: 'Africa/Cairo',
    tier: 3,
    position: 5,
    is_active: true,
  },
  {
    id: 'tasi-market-id',
    slug: 'tasi',
    name: 'Saudi Stock Exchange (Tadawul)',
    short_name: 'TASI',
    country: 'Saudi Arabia',
    flag_emoji: '🇸🇦',
    city: 'Riyadh',
    timezone: 'Asia/Riyadh',
    tier: 3,
    position: 6,
    is_active: true,
  },
  {
    id: 'ase-market-id',
    slug: 'ase',
    name: 'Amman Stock Exchange',
    short_name: 'ASE',
    country: 'Jordan',
    flag_emoji: '🇯🇴',
    city: 'Amman',
    timezone: 'Asia/Amman',
    tier: 3,
    position: 7,
    is_active: true,
  },
  {
    id: 'dfm-market-id',
    slug: 'dfm',
    name: 'Dubai Financial Market',
    short_name: 'DFM',
    country: 'UAE',
    flag_emoji: '🇦🇪',
    city: 'Dubai',
    timezone: 'Asia/Dubai',
    tier: 3,
    position: 8,
    is_active: true,
  },
  {
    id: 'qe-market-id',
    slug: 'qe',
    name: 'Qatar Exchange',
    short_name: 'QE',
    country: 'Qatar',
    flag_emoji: '🇶🇦',
    city: 'Doha',
    timezone: 'Asia/Qatar',
    tier: 3,
    position: 9,
    is_active: true,
  },
  {
    id: 'kse-market-id',
    slug: 'kse',
    name: 'Kuwait Stock Exchange',
    short_name: 'KSE',
    country: 'Kuwait',
    flag_emoji: '🇰🇼',
    city: 'Kuwait City',
    timezone: 'Asia/Kuwait',
    tier: 3,
    position: 10,
    is_active: true,
  },
];
